#
# Syscall definitions. Important to note that some of these names come
# from the glibc headers and some of them come from the
# kernel. Because of that there may be some names that do not mach up
# one to one as I have constructed these tables from both sources. In
# the future they all should be the intrakernel names.
#
# 
NAME_TO_NUMBER = {
    'restart_syscall'         : 0,
    'exit'                    : 1,
    'fork'                    : 2,
    'read'                    : 3,
    'write'                   : 4,
    'open'                    : 5,
    'close'                   : 6,
    'waitpid'                 : 7,
    'creat'                   : 8,
    'link'                    : 9,
    'unlink'                  : 10,
    'execve'                  : 11,
    'chdir'                   : 12,
    'time'                    : 13,
    'mknod'                   : 14,
    'chmod'                   : 15,
    'lchown'                  : 16,
    'break'                   : 17,
    'oldstat'                 : 18,
    'lseek'                   : 19,
    'getpid'                  : 20,
    'mount'                   : 21,
    'umount'                  : 22,
    'setuid'                  : 23,
    'getuid'                  : 24,
    'stime'                   : 25,
    'ptrace'                  : 26,
    'alarm'                   : 27,
    'oldfstat'                : 28,
    'pause'                   : 29,
    'utime'                   : 30,
    'stty'                    : 31,
    'gtty'                    : 32,
    'access'                  : 33,
    'nice'                    : 34,
    'ftime'                   : 35,
    'sync'                    : 36,
    'kill'                    : 37,
    'rename'                  : 38,
    'mkdir'                   : 39,
    'rmdir'                   : 40,
    'dup'                     : 41,
    'pipe'                    : 42,
    'times'                   : 43,
    'prof'                    : 44,
    'brk'                     : 45,
    'setgid'                  : 46,
    'getgid'                  : 47,
    'signal'                  : 48,
    'geteuid'                 : 49,
    'getegid'                 : 50,
    'acct'                    : 51,
    'umount2'                 : 52,
    'lock'                    : 53,
    'ioctl'                   : 54,
    'fcntl'                   : 55,
    'mpx'                     : 56,
    'setpgid'                 : 57,
    'ulimit'                  : 58,
    'oldolduname'             : 59,
    'umask'                   : 60,
    'chroot'                  : 61,
    'ustat'                   : 62,
    'dup2'                    : 63,
    'getppid'                 : 64,
    'getpgrp'                 : 65,
    'setsid'                  : 66,
    'sigaction'               : 67,
    'sgetmask'                : 68,
    'ssetmask'                : 69,
    'setreuid'                : 70,
    'setregid'                : 71,
    'sigsuspend'              : 72,
    'sigpending'              : 73,
    'sethostname'             : 74,
    'setrlimit'               : 75,
    'getrlimit'               : 76,
    'getrusage'               : 77,
    'gettimeofday'            : 78,
    'settimeofday'            : 79,
    'getgroups'               : 80,
    'setgroups'               : 81,
    'select'                  : 82,
    'symlink'                 : 83,
    'oldlstat'                : 84,
    'readlink'                : 85,
    'uselib'                  : 86,
    'swapon'                  : 87,
    'reboot'                  : 88,
    'readdir'                 : 89,
    'mmap'                    : 90,
    'munmap'                  : 91,
    'truncate'                : 92,
    'ftruncate'               : 93,
    'fchmod'                  : 94,
    'fchown'                  : 95,
    'getpriority'             : 96,
    'setpriority'             : 97,
    'profil'                  : 98,
    'statfs'                  : 99,
    'fstatfs'                 : 100,
    'ioperm'                  : 101,
    'socketcall'              : 102,
    'syslog'                  : 103,
    'setitimer'               : 104,
    'getitimer'               : 105,
    'stat'                    : 106,
    'lstat'                   : 107,
    'fstat'                   : 108,
    'olduname'                : 109,
    'iopl'                    : 110,
    'vhangup'                 : 111,
    'idle'                    : 112,
    'vm86old'                 : 113,
    'wait4'                   : 114,
    'swapoff'                 : 115,
    'sysinfo'                 : 116,
    'ipc'                     : 117,
    'fsync'                   : 118,
    'sigreturn'               : 119,
    'clone'                   : 120,
    'setdomainname'           : 121,
    'uname'                   : 122,
    'modify_ldt'              : 123,
    'adjtimex'                : 124,
    'mprotect'                : 125,
    'sigprocmask'             : 126,
    'create_module'           : 127,
    'init_module'             : 128,
    'delete_module'           : 129,
    'get_kernel_syms'         : 130,
    'quotactl'                : 131,
    'getpgid'                 : 132,
    'fchdir'                  : 133,
    'bdflush'                 : 134,
    'sysfs'                   : 135,
    'personality'             : 136,
    'afs_syscall'             : 137,
    'setfsuid'                : 138,
    'setfsgid'                : 139,
    '_llseek'                 : 140,
    'getdents'                : 141,
    '_newselect'              : 142,
    'flock'                   : 143,
    'msync'                   : 144,
    'readv'                   : 145,
    'writev'                  : 146,
    'getsid'                  : 147,
    'fdatasync'               : 148,
    '_sysctl'                 : 149,
    'mlock'                   : 150,
    'munlock'                 : 151,
    'mlockall'                : 152,
    'munlockall'              : 153,
    'sched_setparam'          : 154,
    'sched_getparam'          : 155,
    'sched_setscheduler'      : 156,
    'sched_getscheduler'      : 157,
    'sched_yield'             : 158,
    'sched_get_priority_max'  : 159,
    'sched_get_priority_min'  : 160,
    'sched_rr_get_interval'   : 161,
    'nanosleep'               : 162,
    'mremap'                  : 163,
    'setresuid'               : 164,
    'getresuid'               : 165,
    'vm86'                    : 166,
    'query_module'            : 167,
    'poll'                    : 168,
    'nfsservctl'              : 169,
    'setresgid'               : 170,
    'getresgid'               : 171,
    'prctl'                   : 172,
    'rt_sigreturn'            : 173,
    'rt_sigaction'            : 174,
    'rt_sigprocmask'          : 175,
    'rt_sigpending'           : 176,
    'rt_sigtimedwait'         : 177,
    'rt_sigqueueinfo'         : 178,
    'rt_sigsuspend'           : 179,
    'pread64'                 : 180,
    'pwrite64'                : 181,
    'chown'                   : 182,
    'getcwd'                  : 183,
    'capget'                  : 184,
    'capset'                  : 185,
    'sigaltstack'             : 186,
    'sendfile'                : 187,
    'getpmsg'                 : 188,
    'putpmsg'                 : 189,
    'vfork'                   : 190,
    'ugetrlimit'              : 191,
    'mmap2'                   : 192,
    'truncate64'              : 193,
    'ftruncate64'             : 194,
    'stat64'                  : 195,
    'lstat64'                 : 196,
    'fstat64'                 : 197,
    'lchown32'                : 198,
    'getuid32'                : 199,
    'getgid32'                : 200,
    'geteuid32'               : 201,
    'getegid32'               : 202,
    'setreuid32'              : 203,
    'setregid32'              : 204,
    'getgroups32'             : 205,
    'setgroups32'             : 206,
    'fchown32'                : 207,
    'setresuid32'             : 208,
    'getresuid32'             : 209,
    'setresgid32'             : 210,
    'getresgid32'             : 211,
    'chown32'                 : 212,
    'setuid32'                : 213,
    'setgid32'                : 214,
    'setfsuid32'              : 215,
    'setfsgid32'              : 216,
    'pivot_root'              : 217,
    'mincore'                 : 218,
    'madvise'                 : 219,
    'madvise1'                : 219,
    'getdents64'              : 220,
    'fcntl64'                 : 221,
    'gettid'                  : 224,
    'readahead'               : 225,
    'setxattr'                : 226,
    'lsetxattr'               : 227,
    'fsetxattr'               : 228,
    'getxattr'                : 229,
    'lgetxattr'               : 230,
    'fgetxattr'               : 231,
    'listxattr'               : 232,
    'llistxattr'              : 233,
    'flistxattr'              : 234,
    'removexattr'             : 235,
    'lremovexattr'            : 236,
    'fremovexattr'            : 237,
    'tkill'                   : 238,
    'sendfile64'              : 239,
    'futex'                   : 240,
    'sched_setaffinity'       : 241,
    'sched_getaffinity'       : 242,
    'set_thread_area'         : 243,
    'get_thread_area'         : 244,
    'io_setup'                : 245,
    'io_destroy'              : 246,
    'io_getevents'            : 247,
    'io_submit'               : 248,
    'io_cancel'               : 249,
    'fadvise64'               : 250,
    'exit_group'              : 252,
    'lookup_dcookie'          : 253,
    'epoll_create'            : 254,
    'epoll_ctl'               : 255,
    'epoll_wait'              : 256,
    'remap_file_pages'        : 257,
    'set_tid_address'         : 258,
    'timer_create'            : 259,
    'timer_settime'           : 260,
    'timer_gettime'           : 261,
    'timer_getoverrun'        : 262,
    'timer_delete'            : 263,
    'clock_settime'           : 264,
    'clock_gettime'           : 265,
    'clock_getres'            : 266,
    'clock_nanosleep'         : 267,
    'statfs64'                : 268,
    'fstatfs64'               : 269,
    'tgkill'                  : 270,
    'utimes'                  : 271,
    'fadvise64_64'            : 272,
    'vserver'                 : 273,
    'mbind'                   : 274,
    'get_mempolicy'           : 275,
    'set_mempolicy'           : 276,
    'mq_open'                 : 277,
    'mq_unlink'               : 278,
    'mq_timedsend'            : 279,
    'mq_timedreceive'         : 280,
    'mq_notify'               : 281,
    'mq_getsetattr'           : 282,
    'kexec_load'              : 283,
    'waitid'                  : 284,
    'add_key'                 : 286,
    'request_key'             : 287,
    'keyctl'                  : 288,
    'ioprio_set'              : 289,
    'ioprio_get'              : 290,
    'inotify_init'            : 291,
    'inotify_add_watch'       : 292,
    'inotify_rm_watch'        : 293,
    'migrate_pages'           : 294,
    'openat'                  : 295,
    'mkdirat'                 : 296,
    'mknodat'                 : 297,
    'fchownat'                : 298,
    'futimesat'               : 299,
    'fstatat64'               : 300,
    'unlinkat'                : 301,
    'renameat'                : 302,
    'linkat'                  : 303,
    'symlinkat'               : 304,
    'readlinkat'              : 305,
    'fchmodat'                : 306,
    'faccessat'               : 307,
    'pselect6'                : 308,
    'ppoll'                   : 309,
    'unshare'                 : 310,
    'set_robust_list'         : 311,
    'get_robust_list'         : 312,
    'splice'                  : 313,
    'sync_file_range'         : 314,
    'tee'                     : 315,
    'vmsplice'                : 316,
    'move_pages'              : 317,
    'getcpu'                  : 318,
    'epoll_pwait'             : 319,
    'utimensat'               : 320,
    'signalfd'                : 321,
    'timerfd_create'          : 322,
    'eventfd'                 : 323,
    'fallocate'               : 324,
    'timerfd_settime'         : 325,
    'timerfd_gettime'         : 326,
    'signalfd4'               : 327,
    'eventfd2'                : 328,
    'epoll_create1'           : 329,
    'dup3'                    : 330,
    'pipe2'                   : 331,
    'inotify_init1'           : 332,
    'preadv'                  : 333,
    'pwritev'                 : 334,
    'rt_tgsigqueueinfo'       : 335,
    'perf_event_open'         : 336,

}

NUMBER_TO_NAME = {
    0     : 'restart_syscall',
    1     : 'exit',
    2     : 'fork',
    3     : 'read',
    4     : 'write',
    5     : 'open',
    6     : 'close',
    7     : 'waitpid',
    8     : 'creat',
    9     : 'link',
    10    : 'unlink',
    11    : 'execve',
    12    : 'chdir',
    13    : 'time',
    14    : 'mknod',
    15    : 'chmod',
    16    : 'lchown',
    17    : 'break',
    18    : 'oldstat',
    19    : 'lseek',
    20    : 'getpid',
    21    : 'mount',
    22    : 'umount',
    23    : 'setuid',
    24    : 'getuid',
    25    : 'stime',
    26    : 'ptrace',
    27    : 'alarm',
    28    : 'oldfstat',
    29    : 'pause',
    30    : 'utime',
    31    : 'stty',
    32    : 'gtty',
    33    : 'access',
    34    : 'nice',
    35    : 'ftime',
    36    : 'sync',
    37    : 'kill',
    38    : 'rename',
    39    : 'mkdir',
    40    : 'rmdir',
    41    : 'dup',
    42    : 'pipe',
    43    : 'times',
    44    : 'prof',
    45    : 'brk',
    46    : 'setgid',
    47    : 'getgid',
    48    : 'signal',
    49    : 'geteuid',
    50    : 'getegid',
    51    : 'acct',
    52    : 'umount2',
    53    : 'lock',
    54    : 'ioctl',
    55    : 'fcntl',
    56    : 'mpx',
    57    : 'setpgid',
    58    : 'ulimit',
    59    : 'oldolduname',
    60    : 'umask',
    61    : 'chroot',
    62    : 'ustat',
    63    : 'dup2',
    64    : 'getppid',
    65    : 'getpgrp',
    66    : 'setsid',
    67    : 'sigaction',
    68    : 'sgetmask',
    69    : 'ssetmask',
    70    : 'setreuid',
    71    : 'setregid',
    72    : 'sigsuspend',
    73    : 'sigpending',
    74    : 'sethostname',
    75    : 'setrlimit',
    76    : 'getrlimit',
    77    : 'getrusage',
    78    : 'gettimeofday',
    79    : 'settimeofday',
    80    : 'getgroups',
    81    : 'setgroups',
    82    : 'select',
    83    : 'symlink',
    84    : 'oldlstat',
    85    : 'readlink',
    86    : 'uselib',
    87    : 'swapon',
    88    : 'reboot',
    89    : 'readdir',
    90    : 'mmap',
    91    : 'munmap',
    92    : 'truncate',
    93    : 'ftruncate',
    94    : 'fchmod',
    95    : 'fchown',
    96    : 'getpriority',
    97    : 'setpriority',
    98    : 'profil',
    99    : 'statfs',
    100   : 'fstatfs',
    101   : 'ioperm',
    102   : 'socketcall',
    103   : 'syslog',
    104   : 'setitimer',
    105   : 'getitimer',
    106   : 'stat',
    107   : 'lstat',
    108   : 'fstat',
    109   : 'olduname',
    110   : 'iopl',
    111   : 'vhangup',
    112   : 'idle',
    113   : 'vm86old',
    114   : 'wait4',
    115   : 'swapoff',
    116   : 'sysinfo',
    117   : 'ipc',
    118   : 'fsync',
    119   : 'sigreturn',
    120   : 'clone',
    121   : 'setdomainname',
    122   : 'uname',
    123   : 'modify_ldt',
    124   : 'adjtimex',
    125   : 'mprotect',
    126   : 'sigprocmask',
    127   : 'create_module',
    128   : 'init_module',
    129   : 'delete_module',
    130   : 'get_kernel_syms',
    131   : 'quotactl',
    132   : 'getpgid',
    133   : 'fchdir',
    134   : 'bdflush',
    135   : 'sysfs',
    136   : 'personality',
    137   : 'afs_syscall',
    138   : 'setfsuid',
    139   : 'setfsgid',
    140   : '_llseek',
    141   : 'getdents',
    142   : '_newselect',
    143   : 'flock',
    144   : 'msync',
    145   : 'readv',
    146   : 'writev',
    147   : 'getsid',
    148   : 'fdatasync',
    149   : '_sysctl',
    150   : 'mlock',
    151   : 'munlock',
    152   : 'mlockall',
    153   : 'munlockall',
    154   : 'sched_setparam',
    155   : 'sched_getparam',
    156   : 'sched_setscheduler',
    157   : 'sched_getscheduler',
    158   : 'sched_yield',
    159   : 'sched_get_priority_max',
    160   : 'sched_get_priority_min',
    161   : 'sched_rr_get_interval',
    162   : 'nanosleep',
    163   : 'mremap',
    164   : 'setresuid',
    165   : 'getresuid',
    166   : 'vm86',
    167   : 'query_module',
    168   : 'poll',
    169   : 'nfsservctl',
    170   : 'setresgid',
    171   : 'getresgid',
    172   : 'prctl',
    173   : 'rt_sigreturn',
    174   : 'rt_sigaction',
    175   : 'rt_sigprocmask',
    176   : 'rt_sigpending',
    177   : 'rt_sigtimedwait',
    178   : 'rt_sigqueueinfo',
    179   : 'rt_sigsuspend',
    180   : 'pread64',
    181   : 'pwrite64',
    182   : 'chown',
    183   : 'getcwd',
    184   : 'capget',
    185   : 'capset',
    186   : 'sigaltstack',
    187   : 'sendfile',
    188   : 'getpmsg',
    189   : 'putpmsg',
    190   : 'vfork',
    191   : 'ugetrlimit',
    192   : 'mmap2',
    193   : 'truncate64',
    194   : 'ftruncate64',
    195   : 'stat64',
    196   : 'lstat64',
    197   : 'fstat64',
    198   : 'lchown32',
    199   : 'getuid32',
    200   : 'getgid32',
    201   : 'geteuid32',
    202   : 'getegid32',
    203   : 'setreuid32',
    204   : 'setregid32',
    205   : 'getgroups32',
    206   : 'setgroups32',
    207   : 'fchown32',
    208   : 'setresuid32',
    209   : 'getresuid32',
    210   : 'setresgid32',
    211   : 'getresgid32',
    212   : 'chown32',
    213   : 'setuid32',
    214   : 'setgid32',
    215   : 'setfsuid32',
    216   : 'setfsgid32',
    217   : 'pivot_root',
    218   : 'mincore',
    219   : 'madvise',
    219   : 'madvise1',
    220   : 'getdents64',
    221   : 'fcntl64',
    224   : 'gettid',
    225   : 'readahead',
    226   : 'setxattr',
    227   : 'lsetxattr',
    228   : 'fsetxattr',
    229   : 'getxattr',
    230   : 'lgetxattr',
    231   : 'fgetxattr',
    232   : 'listxattr',
    233   : 'llistxattr',
    234   : 'flistxattr',
    235   : 'removexattr',
    236   : 'lremovexattr',
    237   : 'fremovexattr',
    238   : 'tkill',
    239   : 'sendfile64',
    240   : 'futex',
    241   : 'sched_setaffinity',
    242   : 'sched_getaffinity',
    243   : 'set_thread_area',
    244   : 'get_thread_area',
    245   : 'io_setup',
    246   : 'io_destroy',
    247   : 'io_getevents',
    248   : 'io_submit',
    249   : 'io_cancel',
    250   : 'fadvise64',
    252   : 'exit_group',
    253   : 'lookup_dcookie',
    254   : 'epoll_create',
    255   : 'epoll_ctl',
    256   : 'epoll_wait',
    257   : 'remap_file_pages',
    258   : 'set_tid_address',
    259   : 'timer_create',
    260   : 'timer_settime',
    261   : 'timer_gettime',
    262   : 'timer_getoverrun',
    263   : 'timer_delete',
    264   : 'clock_settime',
    265   : 'clock_gettime',
    266   : 'clock_getres',
    267   : 'clock_nanosleep',
    268   : 'statfs64',
    269   : 'fstatfs64',
    270   : 'tgkill',
    271   : 'utimes',
    272   : 'fadvise64_64',
    273   : 'vserver',
    274   : 'mbind',
    275   : 'get_mempolicy',
    276   : 'set_mempolicy',
    277   : 'mq_open',
    278   : 'mq_unlink',
    279   : 'mq_timedsend',
    280   : 'mq_timedreceive',
    281   : 'mq_notify',
    282   : 'mq_getsetattr',
    283   : 'kexec_load',
    284   : 'waitid',
    286   : 'add_key',
    287   : 'request_key',
    288   : 'keyctl',
    289   : 'ioprio_set',
    290   : 'ioprio_get',
    291   : 'inotify_init',
    292   : 'inotify_add_watch',
    293   : 'inotify_rm_watch',
    294   : 'migrate_pages',
    295   : 'openat',
    296   : 'mkdirat',
    297   : 'mknodat',
    298   : 'fchownat',
    299   : 'futimesat',
    300   : 'fstatat64',
    301   : 'unlinkat',
    302   : 'renameat',
    303   : 'linkat',
    304   : 'symlinkat',
    305   : 'readlinkat',
    306   : 'fchmodat',
    307   : 'faccessat',
    308   : 'pselect6',
    309   : 'ppoll',
    310   : 'unshare',
    311   : 'set_robust_list',
    312   : 'get_robust_list',
    313   : 'splice',
    314   : 'sync_file_range',
    315   : 'tee',
    316   : 'vmsplice',
    317   : 'move_pages',
    318   : 'getcpu',
    319   : 'epoll_pwait',
    320   : 'utimensat',
    321   : 'signalfd',
    322   : 'timerfd_create',
    323   : 'eventfd',
    324   : 'fallocate',
    325   : 'timerfd_settime',
    326   : 'timerfd_gettime',
    327   : 'signalfd4',
    328   : 'eventfd2',
    329   : 'epoll_create1',
    330   : 'dup3',
    331   : 'pipe2',
    332   : 'inotify_init1',
    333   : 'preadv',
    334   : 'pwritev',
    335   : 'rt_tgsigqueueinfo',
    336   : 'perf_event_open',

}


#
# Note that the glibc syscall names and the intrakernel names differ/
#
# INFO: Unknown syscall name newstat.
# INFO: Unknown syscall name newlstat.
# INFO: Unknown syscall name newfstat.
# INFO: Unknown syscall name oldumount.
# INFO: Unknown syscall name socket.
# INFO: Unknown syscall name bind.
# INFO: Unknown syscall name listen.
# INFO: Unknown syscall name shutdown.
# INFO: Unknown syscall name sendmsg.
# INFO: Unknown syscall name sysctl.
# INFO: Unknown syscall name sysctl.
# INFO: Unknown syscall name chown16.
# INFO: Unknown syscall name lchown16.
# INFO: Unknown syscall name fchown16.
# INFO: Unknown syscall name setregid16.
# INFO: Unknown syscall name setgid16.
# INFO: Unknown syscall name setreuid16.
# INFO: Unknown syscall name setuid16.
# INFO: Unknown syscall name setresuid16.
# INFO: Unknown syscall name getresuid16.
# INFO: Unknown syscall name setresgid16.
# INFO: Unknown syscall name getresgid16.
# INFO: Unknown syscall name setfsuid16.
# INFO: Unknown syscall name setfsgid16.
# INFO: Unknown syscall name getgroups16.
# INFO: Unknown syscall name setgroups16.
# INFO: Unknown syscall name getuid16.
# INFO: Unknown syscall name geteuid16.
# INFO: Unknown syscall name getgid16.
# INFO: Unknown syscall name getegid16.
# INFO: Unknown syscall name newuname.
# INFO: Unknown syscall name gethostname.
# INFO: Unknown syscall name shmget.
# INFO: Unknown syscall name shmctl.
# INFO: Unknown syscall name shmat.
# INFO: Unknown syscall name shmdt.
# INFO: Unknown syscall name msgget.
# INFO: Unknown syscall name msgctl.
# INFO: Unknown syscall name semget.

NAMES_TO_ARGS = {
    'access': [('const char __user *', 'filename'), ('int', 'mode')],
    'acct': [('const char __user *', 'name')],
    'adjtimex': [('struct timex __user *', 'txc_p')],
    'alarm': [('unsigned int', 'seconds')],
    'bdflush': [('int', 'func'), ('long', 'data')],
    'bind': [('int', 'fd'),
             ('struct sockaddr __user *', 'umyaddr'),
             ('int', 'addrlen')],
    'brk': [('unsigned long', 'brk')],
    'capget': [('cap_user_header_t', 'header'), ('cap_user_data_t', 'dataptr')],
    'capset': [('cap_user_header_t', 'header'),
               ('const cap_user_data_t', 'data')],
    'chdir': [('const char __user *', 'filename')],
    'chmod': [('const char __user *', 'filename'), ('mode_t', 'mode')],
    'chown': [('const char __user *', 'filename'),
              ('uid_t', 'user'),
              ('gid_t', 'group')],
    'chown16': [('const char __user *', 'filename'),
                ('old_uid_t', 'user'),
                ('old_gid_t', 'group')],
    'chroot': [('const char __user *', 'filename')],
    'close': [('unsigned int', 'fd')],
    'creat': [('const char __user *', 'pathname'), ('int', 'mode')],
    'dup': [('unsigned int', 'fildes')],
    'dup2': [('unsigned int', 'oldfd'), ('unsigned int', 'newfd')],
    'dup3': [('unsigned int', 'oldfd'),
             ('unsigned int', 'newfd'),
             ('int', 'flags')],
    'epoll_create': [('int', 'size')],
    'epoll_create1': [('int', 'flags')],
    'eventfd': [('unsigned int', 'count')],
    'eventfd2': [('unsigned int', 'count'), ('int', 'flags')],
    'exit': [('int', 'error_code')],
    'exit_group': [('int', 'error_code')],
    'faccessat': [('int', 'dfd'),
                  ('const char __user *', 'filename'),
                  ('int', 'mode')],
    'fchdir': [('unsigned int', 'fd')],
    'fchmod': [('unsigned int', 'fd'), ('mode_t', 'mode')],
    'fchmodat': [('int', 'dfd'),
                 ('const char __user *', 'filename'),
                 ('mode_t', 'mode')],
    'fchown': [('unsigned int', 'fd'), ('uid_t', 'user'), ('gid_t', 'group')],
    'fchown16': [('unsigned int', 'fd'),
                 ('old_uid_t', 'user'),
                 ('old_gid_t', 'group')],
    'fcntl': [('unsigned int', 'fd'),
              ('unsigned int', 'cmd'),
              ('unsigned long', 'arg')],
    'fdatasync': [('unsigned int', 'fd')],
    'flistxattr': [('int', 'fd'), ('char __user *', 'list'), ('size_t', 'size')],
    'flock': [('unsigned int', 'fd'), ('unsigned int', 'cmd')],
    'fremovexattr': [('int', 'fd'), ('const char __user *', 'name')],
    'fstat': [('unsigned int', 'fd'),
              ('struct __old_kernel_stat __user *', 'statbuf')],
    'fstat64': [('unsigned long', 'fd'), ('struct stat64 __user *', 'statbuf')],
    'fstatfs': [('unsigned int', 'fd'), ('struct statfs __user *', 'buf')],
    'fstatfs64': [('unsigned int', 'fd'),
                  ('size_t', 'sz'),
                  ('struct statfs64 __user *', 'buf')],
    'fsync': [('unsigned int', 'fd')],
    'ftruncate': [('unsigned int', 'fd'), ('unsigned long', 'length')],
    'getcwd': [('char __user *', 'buf'), ('unsigned long', 'size')],
    'getegid': [],
    'getegid16': [],
    'geteuid': [],
    'geteuid16': [],
    'getgid': [],
    'getgid16': [],
    'getgroups': [('int', 'gidsetsize'), ('gid_t __user *', 'grouplist')],
    'getgroups16': [('int', 'gidsetsize'), ('old_gid_t __user *', 'grouplist')],
    'gethostname': [('char __user *', 'name'), ('int', 'len')],
    'getitimer': [('int', 'which'), ('struct itimerval __user *', 'value')],
    'getpgid': [('pid_t', 'pid')],
    'getpgrp': [],
    'getpid': [],
    'getppid': [],
    'getpriority': [('int', 'which'), ('int', 'who')],
    'getresgid': [('gid_t __user *', 'rgid'),
                  ('gid_t __user *', 'egid'),
                  ('gid_t __user *', 'sgid')],
    'getresgid16': [('old_gid_t __user *', 'rgid'),
                    ('old_gid_t __user *', 'egid'),
                    ('old_gid_t __user *', 'sgid')],
    'getresuid': [('uid_t __user *', 'ruid'),
                  ('uid_t __user *', 'euid'),
                  ('uid_t __user *', 'suid')],
    'getresuid16': [('old_uid_t __user *', 'ruid'),
                    ('old_uid_t __user *', 'euid'),
                    ('old_uid_t __user *', 'suid')],
    'getrlimit': [('unsigned int', 'resource'),
               ('struct rlimit __user *', 'rlim')],
    'getrusage': [('int', 'who'), ('struct rusage __user *', 'ru')],
    'getsid': [('pid_t', 'pid')],
    'gettid': [],
    'getuid': [],
    'getuid16': [],
    'inotify_init': [],
    'inotify_init1': [('int', 'flags')],
    'inotify_rm_watch': [('int', 'fd'), ('__s32', 'wd')],
    'io_destroy': [('aio_context_t', 'ctx')],
    'io_setup': [('unsigned', 'nr_events'), ('aio_context_t __user *', 'ctxp')],
    'ioctl': [('unsigned int', 'fd'),
              ('unsigned int', 'cmd'),
              ('unsigned long', 'arg')],
    'ioprio_get': [('int', 'which'), ('int', 'who')],
    'ioprio_set': [('int', 'which'), ('int', 'who'), ('int', 'ioprio')],
    'kill': [('pid_t', 'pid'), ('int', 'sig')],
    'lchown': [('const char __user *', 'filename'),
               ('uid_t', 'user'),
               ('gid_t', 'group')],
    'lchown16': [('const char __user *', 'filename'),
                 ('old_uid_t', 'user'),
                 ('old_gid_t', 'group')],
    'link': [('const char __user *', 'oldname'),
             ('const char __user *', 'newname')],
    'listen': [('int', 'fd'), ('int', 'backlog')],
    'lseek': [('unsigned int', 'fd'),
              ('off_t', 'offset'),
              ('unsigned int', 'origin')],
    'lstat': [('char __user *', 'filename'),
              ('struct __old_kernel_stat __user *', 'statbuf')],
    'lstat64': [('char __user *', 'filename'),
                ('struct stat64 __user *', 'statbuf')],
    'madvise': [('unsigned long', 'start'),
                ('size_t', 'len_in'),
                ('int', 'behavior')],
    'mkdir': [('const char __user *', 'pathname'), ('int', 'mode')],
    'mkdirat': [('int', 'dfd'),
                ('const char __user *', 'pathname'),
                ('int', 'mode')],
    'mknod': [('const char __user *', 'filename'),
              ('int', 'mode'),
              ('unsigned', 'dev')],
    'mlock': [('unsigned long', 'start'), ('size_t', 'len')],
    'mlockall': [('int', 'flags')],
    'mq_unlink': [('const char __user *', 'u_name')],
    'msgctl': [('int', 'msqid'),
            ('int', 'cmd'),
               ('struct msqid_ds __user *', 'buf')],
    'msgget': [('key_t', 'key'), ('int', 'msgflg')],
    'msync': [('unsigned long', 'start'), ('size_t', 'len'), ('int', 'flags')],
    'munlock': [('unsigned long', 'start'), ('size_t', 'len')],
    'munlockall': [],
    'munmap': [('unsigned long', 'addr'), ('size_t', 'len')],
    'newfstat': [('unsigned int', 'fd'), ('struct stat __user *', 'statbuf')],
    'newlstat': [('char __user *', 'filename'),
                 ('struct stat __user *', 'statbuf')],
    'newstat': [('char __user *', 'filename'),
                ('struct stat __user *', 'statbuf')],
    'newuname': [('struct new_utsname __user *', 'name')],
    'nice': [('int', 'increment')],
    'oldumount': [('char __user *', 'name')],
    'open': [('const char __user *', 'filename'),
             ('int', 'flags'),
             ('int', 'mode')],
    'pause': [],
    'personality': [('u_long', 'personality')],
    'pipe': [('int __user *', 'fildes')],
    'pipe2': [('int __user *', 'fildes'), ('int', 'flags')],
    'ptrace': [('long', 'request'),
               ('long', 'pid'),
               ('long', 'addr'),
               ('long', 'data')],
    'read': [('unsigned int', 'fd'),
             ('char __user *', 'buf'),
             ('size_t', 'count')],
    'rename': [('const char __user *', 'oldname'),
               ('const char __user *', 'newname')],
    'restart_syscall': [],
    'rmdir': [('const char __user *', 'pathname')],
    'rt_sigpending': [('sigset_t __user *', 'set'), ('size_t', 'sigsetsize')],
    'rt_sigsuspend': [('sigset_t __user *', 'unewset'), ('size_t', 'sigsetsize')],
    'sched_get_priority_max': [('int', 'policy')],
    'sched_get_priority_min': [('int', 'policy')],
    'sched_getparam': [('pid_t', 'pid'),
                       ('struct sched_param __user *', 'param')],
    'sched_getscheduler': [('pid_t', 'pid')],
    'sched_setparam': [('pid_t', 'pid'),
                       ('struct sched_param __user *', 'param')],
    'sched_yield': [],
    'semget': [('key_t', 'key'), ('int', 'nsems'), ('int', 'semflg')],
    'sendfile': [('int', 'out_fd'),
                 ('int', 'in_fd'),
                 ('off_t __user *', 'offset'),
                 ('size_t', 'count')],
    'sendfile64': [('int', 'out_fd'),
                   ('int', 'in_fd'),
                   ('loff_t __user *', 'offset'),
                   ('size_t', 'count')],
    'sendmsg': [('int', 'fd'),
                ('struct msghdr __user *', 'msg'),
                ('unsigned', 'flags')],
    'set_tid_address': [('int __user *', 'tidptr')],
    'setdomainname': [('char __user *', 'name'), ('int', 'len')],
    'setfsgid': [('gid_t', 'gid')],
    'setfsgid16': [('old_gid_t', 'gid')],
    'setfsuid': [('uid_t', 'uid')],
    'setfsuid16': [('old_uid_t', 'uid')],
    'setgid': [('gid_t', 'gid')],
    'setgid16': [('old_gid_t', 'gid')],
    'setgroups': [('int', 'gidsetsize'), ('gid_t __user *', 'grouplist')],
    'setgroups16': [('int', 'gidsetsize'), ('old_gid_t __user *', 'grouplist')],
    'sethostname': [('char __user *', 'name'), ('int', 'len')],
    'setpgid': [('pid_t', 'pid'), ('pid_t', 'pgid')],
    'setpriority': [('int', 'which'), ('int', 'who'), ('int', 'niceval')],
    'setregid': [('gid_t', 'rgid'), ('gid_t', 'egid')],
    'setregid16': [('old_gid_t', 'rgid'), ('old_gid_t', 'egid')],
    'setresgid': [('gid_t', 'rgid'), ('gid_t', 'egid'), ('gid_t', 'sgid')],
    'setresgid16': [('old_gid_t', 'rgid'),
                    ('old_gid_t', 'egid'),
                    ('old_gid_t', 'sgid')],
    'setresuid': [('uid_t', 'ruid'), ('uid_t', 'euid'), ('uid_t', 'suid')],
    'setresuid16': [('old_uid_t', 'ruid'),
                    ('old_uid_t', 'euid'),
                    ('old_uid_t', 'suid')],
    'setreuid': [('uid_t', 'ruid'), ('uid_t', 'euid')],
    'setreuid16': [('old_uid_t', 'ruid'), ('old_uid_t', 'euid')],
    'setrlimit': [('unsigned int', 'resource'),
                  ('struct rlimit __user *', 'rlim')],
    'setsid': [],
    'setuid': [('uid_t', 'uid')],
    'setuid16': [('old_uid_t', 'uid')],
    'sgetmask': [],
    'shmat': [('int', 'shmid'), ('char __user *', 'shmaddr'), ('int', 'shmflg')],
    'shmctl': [('int', 'shmid'),
               ('int', 'cmd'),
               ('struct shmid_ds __user *', 'buf')],
    'shmdt': [('char __user *', 'shmaddr')],
    'shmget': [('key_t', 'key'), ('size_t', 'size'), ('int', 'shmflg')],
    'shutdown': [('int', 'fd'), ('int', 'how')],
    'signal': [('int', 'sig'), ('__sighandler_t', 'handler')],
    'sigpending': [('old_sigset_t __user *', 'set')],
    'socket': [('int', 'family'), ('int', 'type'), ('int', 'protocol')],
    'socketcall': [('int', 'call'), ('unsigned long __user *', 'args')],
 'ssetmask': [('int', 'newmask')],
    'stat': [('char __user *', 'filename'),
             ('struct __old_kernel_stat __user *', 'statbuf')],
    'stat64': [('char __user *', 'filename'),
               ('struct stat64 __user *', 'statbuf')],
    'statfs': [('const char __user *', 'pathname'),
               ('struct statfs __user *', 'buf')],
    'statfs64': [('const char __user *', 'pathname'),
                 ('size_t', 'sz'),
                 ('struct statfs64 __user *', 'buf')],
    'stime': [('time_t __user *', 'tptr')],
    'swapoff': [('const char __user *', 'specialfile')],
    'swapon': [('const char __user *', 'specialfile'), ('int', 'swap_flags')],
    'symlink': [('const char __user *', 'oldname'),
                ('const char __user *', 'newname')],
    'sync': [],
    'sysctl': [('struct __sysctl_args __user *', 'args')],
    'sysfs': [('int', 'option'),
              ('unsigned long', 'arg1'),
              ('unsigned long', 'arg2')],
    'sysinfo': [('struct sysinfo __user *', 'info')],
    'syslog': [('int', 'type'), ('char __user *', 'buf'), ('int', 'len')],
    'tee': [('int', 'fdin'),
            ('int', 'fdout'),
            ('size_t', 'len'),
            ('unsigned int', 'flags')],
    'tgkill': [('pid_t', 'tgid'), ('pid_t', 'pid'), ('int', 'sig')],
    'time': [('time_t __user *', 'tloc')],
    'timer_delete': [('timer_t', 'timer_id')],
    'timer_getoverrun': [('timer_t', 'timer_id')],
    'timerfd_create': [('int', 'clockid'), ('int', 'flags')],
    'timerfd_gettime': [('int', 'ufd'), ('struct itimerspec __user *', 'otmr')],
    'times': [('struct tms __user *', 'tbuf')],
    'tkill': [('pid_t', 'pid'), ('int', 'sig')],
    'truncate': [('const char __user *', 'path'), ('unsigned long', 'length')],
    'umask': [('int', 'mask')],
    'umount': [('char __user *', 'name'), ('int', 'flags')],
    'uname': [('struct new_utsname __user *', 'name')],
    'unlink': [('const char __user *', 'pathname')],
    'unlinkat': [('int', 'dfd'),
                 ('const char __user *', 'pathname'),
                 ('int', 'flag')],
    'unshare': [('unsigned long', 'unshare_flags')],
    'uselib': [('const char __user *', 'library')],
    'ustat': [('unsigned', 'dev'), ('struct ustat __user *', 'ubuf')],
    'utime': [('char __user *', 'filename'),
              ('struct utimbuf __user *', 'times')],
    'vhangup': [],
    'waitpid': [('pid_t', 'pid'),
                ('int __user *', 'stat_addr'),
                ('int', 'options')]}

PARAMS_BY_NUMBER = {
    0: [],
    1: [('int', 'error_code')],
    3: [('unsigned int', 'fd'), ('char __user *', 'buf'), ('size_t', 'count')],
    5: [('const char __user *', 'filename'), ('int', 'flags'), ('int', 'mode')],
    6: [('unsigned int', 'fd')],
    7: [('pid_t', 'pid'), ('int __user *', 'stat_addr'), ('int', 'options')],
    8: [('const char __user *', 'pathname'), ('int', 'mode')],
    9: [('const char __user *', 'oldname'), ('const char __user *', 'newname')],
    10: [('const char __user *', 'pathname')],
    12: [('const char __user *', 'filename')],
    13: [('time_t __user *', 'tloc')],
    14: [('const char __user *', 'filename'),
         ('int', 'mode'),
         ('unsigned', 'dev')],
    15: [('const char __user *', 'filename'), ('mode_t', 'mode')],
    16: [('const char __user *', 'filename'),
         ('uid_t', 'user'),
         ('gid_t', 'group')],
    19: [('unsigned int', 'fd'), ('off_t', 'offset'), ('unsigned int', 'origin')],
    20: [],
    22: [('char __user *', 'name'), ('int', 'flags')],
    23: [('uid_t', 'uid')],
    24: [],
    25: [('time_t __user *', 'tptr')],
    26: [('long', 'request'),
         ('long', 'pid'),
         ('long', 'addr'),
         ('long', 'data')],
    27: [('unsigned int', 'seconds')],
    29: [],
    30: [('char __user *', 'filename'), ('struct utimbuf __user *', 'times')],
    33: [('const char __user *', 'filename'), ('int', 'mode')],
    34: [('int', 'increment')],
    36: [],
    37: [('pid_t', 'pid'), ('int', 'sig')],
    38: [('const char __user *', 'oldname'), ('const char __user *', 'newname')],
    39: [('const char __user *', 'pathname'), ('int', 'mode')],
    40: [('const char __user *', 'pathname')],
    41: [('unsigned int', 'fildes')],
    42: [('int __user *', 'fildes')],
    43: [('struct tms __user *', 'tbuf')],
    45: [('unsigned long', 'brk')],
    46: [('gid_t', 'gid')],
    47: [],
    48: [('int', 'sig'), ('__sighandler_t', 'handler')],
    49: [],
    50: [],
    51: [('const char __user *', 'name')],
    54: [('unsigned int', 'fd'),
         ('unsigned int', 'cmd'),
         ('unsigned long', 'arg')],
    55: [('unsigned int', 'fd'),
         ('unsigned int', 'cmd'),
         ('unsigned long', 'arg')],
    57: [('pid_t', 'pid'), ('pid_t', 'pgid')],
    60: [('int', 'mask')],
    61: [('const char __user *', 'filename')],
    62: [('unsigned', 'dev'), ('struct ustat __user *', 'ubuf')],
    63: [('unsigned int', 'oldfd'), ('unsigned int', 'newfd')],
    64: [],
    65: [],
    66: [],
    68: [],
    69: [('int', 'newmask')],
    70: [('uid_t', 'ruid'), ('uid_t', 'euid')],
    71: [('gid_t', 'rgid'), ('gid_t', 'egid')],
    73: [('old_sigset_t __user *', 'set')],
    74: [('char __user *', 'name'), ('int', 'len')],
    75: [('unsigned int', 'resource'), ('struct rlimit __user *', 'rlim')],
    76: [('unsigned int', 'resource'), ('struct rlimit __user *', 'rlim')],
    77: [('int', 'who'), ('struct rusage __user *', 'ru')],
    80: [('int', 'gidsetsize'), ('gid_t __user *', 'grouplist')],
    81: [('int', 'gidsetsize'), ('gid_t __user *', 'grouplist')],
    83: [('const char __user *', 'oldname'), ('const char __user *', 'newname')],
    86: [('const char __user *', 'library')],
    87: [('const char __user *', 'specialfile'), ('int', 'swap_flags')],
    91: [('unsigned long', 'addr'), ('size_t', 'len')],
    92: [('const char __user *', 'path'), ('unsigned long', 'length')],
    93: [('unsigned int', 'fd'), ('unsigned long', 'length')],
    94: [('unsigned int', 'fd'), ('mode_t', 'mode')],
    95: [('unsigned int', 'fd'), ('uid_t', 'user'), ('gid_t', 'group')],
    96: [('int', 'which'), ('int', 'who')],
    97: [('int', 'which'), ('int', 'who'), ('int', 'niceval')],
    99: [('const char __user *', 'pathname'), ('struct statfs __user *', 'buf')],
    100: [('unsigned int', 'fd'), ('struct statfs __user *', 'buf')],
    102: [('int', 'call'), ('unsigned long __user *', 'args')],
    103: [('int', 'type'), ('char __user *', 'buf'), ('int', 'len')],
    105: [('int', 'which'), ('struct itimerval __user *', 'value')],
    106: [('char __user *', 'filename'),
          ('struct __old_kernel_stat __user *', 'statbuf')],
    107: [('char __user *', 'filename'),
          ('struct __old_kernel_stat __user *', 'statbuf')],
    108: [('unsigned int', 'fd'),
          ('struct __old_kernel_stat __user *', 'statbuf')],
    111: [],
    115: [('const char __user *', 'specialfile')],
    116: [('struct sysinfo __user *', 'info')],
    118: [('unsigned int', 'fd')],
    121: [('char __user *', 'name'), ('int', 'len')],
    122: [('struct new_utsname __user *', 'name')],
    124: [('struct timex __user *', 'txc_p')],
    132: [('pid_t', 'pid')],
    133: [('unsigned int', 'fd')],
    134: [('int', 'func'), ('long', 'data')],
    135: [('int', 'option'),
          ('unsigned long', 'arg1'),
          ('unsigned long', 'arg2')],
    136: [('u_long', 'personality')],
    138: [('uid_t', 'uid')],
    139: [('gid_t', 'gid')],
    143: [('unsigned int', 'fd'), ('unsigned int', 'cmd')],
    144: [('unsigned long', 'start'), ('size_t', 'len'), ('int', 'flags')],
    147: [('pid_t', 'pid')],
    148: [('unsigned int', 'fd')],
    150: [('unsigned long', 'start'), ('size_t', 'len')],
    151: [('unsigned long', 'start'), ('size_t', 'len')],
    152: [('int', 'flags')],
    153: [],
    154: [('pid_t', 'pid'), ('struct sched_param __user *', 'param')],
    155: [('pid_t', 'pid'), ('struct sched_param __user *', 'param')],
    157: [('pid_t', 'pid')],
    158: [],
    159: [('int', 'policy')],
    160: [('int', 'policy')],
    164: [('uid_t', 'ruid'), ('uid_t', 'euid'), ('uid_t', 'suid')],
    165: [('uid_t __user *', 'ruid'),
          ('uid_t __user *', 'euid'),
          ('uid_t __user *', 'suid')],
    170: [('gid_t', 'rgid'), ('gid_t', 'egid'), ('gid_t', 'sgid')],
    171: [('gid_t __user *', 'rgid'),
          ('gid_t __user *', 'egid'),
          ('gid_t __user *', 'sgid')],
    176: [('sigset_t __user *', 'set'), ('size_t', 'sigsetsize')],
    179: [('sigset_t __user *', 'unewset'), ('size_t', 'sigsetsize')],
    182: [('const char __user *', 'filename'),
          ('uid_t', 'user'),
          ('gid_t', 'group')],
    183: [('char __user *', 'buf'), ('unsigned long', 'size')],
    184: [('cap_user_header_t', 'header'), ('cap_user_data_t', 'dataptr')],
    185: [('cap_user_header_t', 'header'), ('const cap_user_data_t', 'data')],
    187: [('int', 'out_fd'),
          ('int', 'in_fd'),
          ('off_t __user *', 'offset'),
          ('size_t', 'count')],
    195: [('char __user *', 'filename'), ('struct stat64 __user *', 'statbuf')],
    196: [('char __user *', 'filename'), ('struct stat64 __user *', 'statbuf')],
    197: [('unsigned long', 'fd'), ('struct stat64 __user *', 'statbuf')],
    219: [('unsigned long', 'start'), ('size_t', 'len_in'), ('int', 'behavior')],
    224: [],
    234: [('int', 'fd'), ('char __user *', 'list'), ('size_t', 'size')],
    237: [('int', 'fd'), ('const char __user *', 'name')],
    238: [('pid_t', 'pid'), ('int', 'sig')],
    239: [('int', 'out_fd'),
          ('int', 'in_fd'),
          ('loff_t __user *', 'offset'),
          ('size_t', 'count')],
    245: [('unsigned', 'nr_events'), ('aio_context_t __user *', 'ctxp')],
    246: [('aio_context_t', 'ctx')],
    252: [('int', 'error_code')],
    254: [('int', 'size')],
    258: [('int __user *', 'tidptr')],
    262: [('timer_t', 'timer_id')],
    263: [('timer_t', 'timer_id')],
    268: [('const char __user *', 'pathname'),
          ('size_t', 'sz'),
          ('struct statfs64 __user *', 'buf')],
    269: [('unsigned int', 'fd'),
          ('size_t', 'sz'),
          ('struct statfs64 __user *', 'buf')],
    270: [('pid_t', 'tgid'), ('pid_t', 'pid'), ('int', 'sig')],
    278: [('const char __user *', 'u_name')],
    289: [('int', 'which'), ('int', 'who'), ('int', 'ioprio')],
    290: [('int', 'which'), ('int', 'who')],
    291: [],
    293: [('int', 'fd'), ('__s32', 'wd')],
    296: [('int', 'dfd'), ('const char __user *', 'pathname'), ('int', 'mode')],
    301: [('int', 'dfd'), ('const char __user *', 'pathname'), ('int', 'flag')],
    306: [('int', 'dfd'),
          ('const char __user *', 'filename'),
          ('mode_t', 'mode')],
    307: [('int', 'dfd'), ('const char __user *', 'filename'), ('int', 'mode')],
    310: [('unsigned long', 'unshare_flags')],
    315: [('int', 'fdin'),
          ('int', 'fdout'),
          ('size_t', 'len'),
          ('unsigned int', 'flags')],
    322: [('int', 'clockid'), ('int', 'flags')],
    323: [('unsigned int', 'count')],
    326: [('int', 'ufd'), ('struct itimerspec __user *', 'otmr')],
    328: [('unsigned int', 'count'), ('int', 'flags')],
    329: [('int', 'flags')],
    330: [('unsigned int', 'oldfd'), ('unsigned int', 'newfd'), ('int', 'flags')],
    331: [('int __user *', 'fildes'), ('int', 'flags')],
    332: [('int', 'flags')]}

